"""Add has_time column to tasks table

Revision ID: 3ab18eaa41a3
Revises: ed13344a5088
Create Date: 2025-04-27 18:56:51.126190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab18eaa41a3'
down_revision: Union[str, None] = 'ed13344a5088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_time', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('has_time')

    # ### end Alembic commands ###
