"""Remove user_id (added by error) from tasks table

Revision ID: ed13344a5088
Revises: 173265f4ec25
Create Date: 2025-04-26 18:05:37.832421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed13344a5088'
down_revision: Union[str, None] = '173265f4ec25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_user_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_tasks_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
